name: pre-commit

on:
  pull_request:
    branches: [main]
  push:
    branches: ["**"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - uses: snok/install-poetry@v1
      with:
        version: 1.6.1
    - name: Install protobuf compiler
      run: sudo apt-get update && sudo apt install -y protobuf-compiler build-essential
    - name: Install project
      run: poetry install --no-interaction
    - uses: pre-commit/action@v3.0.1